第６講課題②
kazuoikeda1411/lecture06 pull request #2
Opened 2022-11-29 04:12 UTC by kazuoikeda1411

第６講課題①の内容を変更して再PRしました。
ご確認お願いいたします。
変更内容は以下の通りです。
・controllerとしてHelloControllerクラスを作成し、inputメソッド・resultメソッド・setGreetingAndTodayDateを作成した。
・HTMLファイルをtmp_input・tmp_resultに分け、入力画面と出力画面を表示可能とさせた。
・使用データをmodelのFdatファイルに定義した。

実行内容
１：入力画面にて言語の選択、年齢の入力後、出力ボタンを押す
![Pasted Graphic 33](https://user-images.githubusercontent.com/118358124/204436919-c07e311b-1f44-428d-a8de-673c2cf3a530.png)
２：選択した言語に対応する挨拶＋出力日時に加え、年齢が出力される
![Pasted Graphic 34](https://user-images.githubusercontent.com/118358124/204436967-0dd5a609-0eb7-4693-ab26-8587085d6556.png)

2022-12-01 00:57 UTC, YudaiNoda3576 reviewed
コメントしています！
画面の作成にも挑戦して頂いてとても良いとおもいました！
Thymeleafの使い方もいい感じです！

2022-12-01 00:57 UTC, YudaiNoda3576 commented on HelloWorld/src/main/java/com/raisetech/HelloWorld/controller/HelloController.java
> +	@GetMapping ("/input")
URLのパスの命名についてですが、Restの原則に則って考えて欲しいです！

FYI
https://learn.microsoft.com/ja-jp/azure/architecture/best-practices/api-design

2022-12-01 00:57 UTC, YudaiNoda3576 commented on HelloWorld/src/main/java/com/raisetech/HelloWorld/controller/HelloController.java
> +		model.addAttribute("fdat", new FDat());
fdatという命名って一般的な業界用語とかなのでしょうか？？
もしそうでなければ意味が誰から見ても通るものに変更してください:pray:

2022-12-01 00:57 UTC, YudaiNoda3576 commented on HelloWorld/src/main/java/com/raisetech/HelloWorld/controller/HelloController.java
> +	private void setGreetingAndTodayDate(FDat fdat) {
メソッドやクラスには単一責任の原則というものがありまして、
今回のように挨拶をするという振る舞いと本日の日付を返すという振る舞いは多重責務にあたりアンチパターンとされています。
なので、ここは振る舞いごとにメソッドを分けるべきですね！

これを意識すると保守しやすいコードになったりテストしやすいコードになったりしていくので意識して行ってください！

2022-12-01 00:57 UTC, YudaiNoda3576 commented on HelloWorld/src/main/java/com/raisetech/HelloWorld/controller/HelloController.java
> +		String isGreeting = "";
メソッドの命名からこの変数はboolean型であるのが適切ですかね！

2022-12-01 00:57 UTC, YudaiNoda3576 commented on HelloWorld/src/main/java/com/raisetech/HelloWorld/controller/HelloController.java
> +		String isGreeting = "";
実態は文字列が入ることが正のようなので、変数名を考え直してください！

2022-12-01 10:23 UTC, kazuoikeda1411 commented on HelloWorld/src/main/java/com/raisetech/HelloWorld/controller/HelloController.java
> +	@GetMapping ("/input")
URLのパス名を以下に変更しました。
・/input→/language-age
・/result→/self-introduction

2022-12-01 10:27 UTC, kazuoikeda1411 commented on HelloWorld/src/main/java/com/raisetech/HelloWorld/controller/HelloController.java
> +		model.addAttribute("fdat", new FDat());
参考書（ふりがなプログラミング）で参考にしたコードにfdatと記載してあっただけで、一般的な業界用語とかではないかなと思います。
取得しているデータは言語と年齢なのでlanguageAgeに変更しました。

2022-12-01 10:40 UTC, kazuoikeda1411 commented on HelloWorld/src/main/java/com/raisetech/HelloWorld/controller/HelloController.java
> +	private void setGreetingAndTodayDate(FDat fdat) {
振る舞いごとにメソッドを分けていく意識は持っていなかったです。。。
以後気をつけていきます！

setGreetingAndTodayDateをsetGreetingとsetTodayDateに分けました。

2022-12-01 11:04 UTC, kazuoikeda1411 commented on HelloWorld/src/main/java/com/raisetech/HelloWorld/controller/HelloController.java
> +		String isGreeting = "";
指摘箇所がどこなのかわからず、修正しておりません。
大変申し訳ないのですがもう少し詳しくご教示いただけますと幸いです。

2022-12-01 13:52 UTC, kazuoikeda1411 commented on HelloWorld/src/main/java/com/raisetech/HelloWorld/controller/HelloController.java
> +		String isGreeting = "";
変数の命名法をあらためて調べていたら以下の記載がありました。
・boolean型の変数やboolean型を戻すメソッドは「is～」「has～」「can～」という定義をすることがあります。

ここの指摘箇所はisGreetingと考えたのですがいかがでしょうか？
修正案としては"greeting"や"nationalGreeting"がいいのかなと思いました。。。

2022-12-01 21:37 UTC, YudaiNoda3576 requested changes
コメントしています〜

こちらも確認おねがいします！
https://github.com/kazuoikeda1411/lecture06/pull/2#discussion_r1037569178

2022-12-01 21:37 UTC, YudaiNoda3576 commented on HelloWorld/src/main/java/com/raisetech/HelloWorld/controller/HelloController.java
> +		String isGreeting = "";
`greeting`で良いとおもいます！
より具体的にするには`national`がついていたほうが良いと思うのですが、これを付けるかどうかはシステムの仕様などによって変わります。
例えば、日本語の挨拶と外国語の挨拶を明示的に分けてとシステムの処理が分岐する場合などですね。
今回は外国語かどうかは条件の分岐に関与しないので`greeting`で十分という判断です！

2022-12-01 21:37 UTC, YudaiNoda3576 commented on HelloWorld/src/main/java/com/raisetech/HelloWorld/controller/HelloController.java
> +	@GetMapping ("/language-age")
Restの原則に則ると、パスは複数形にすべきというものがあります。なので複数形にしましょう

↓ここからは対応不要です↓
また、取得するリソースを表現するので名詞で表現するという原則もあります。
なので対応頂いた内容で問題はないのですが、`language-age`という命名だと具体的すぎるかなと思います！

例えば、仕様変更があって緯度経度も返して欲しいみたいな要望が入った瞬間に今のパス名が不適切になります。
なので、パス名を具体的にしすぎると柔軟性が損なわれる可能性があるということだけ頭の片隅に入れておいてください:pray:

2022-12-01 21:37 UTC, YudaiNoda3576 commented on HelloWorld/src/main/java/com/raisetech/HelloWorld/controller/HelloController.java
> +		model.addAttribute("languageAge", new FDat());
FDatがまだ残ってますね！

2022-12-01 21:37 UTC, YudaiNoda3576 commented on HelloWorld/src/main/java/com/raisetech/HelloWorld/controller/HelloController.java
> +	public String selfIntroduction(
`set`という接頭辞が違和感ありますね!
ここでは`set`しているのでしょうか？？
またL18では名詞なのでそことの統一感がないのも違和感があります。

2022-12-01 21:37 UTC, YudaiNoda3576 commented on HelloWorld/src/main/java/com/raisetech/HelloWorld/controller/HelloController.java
> +	public String languageAge(Model model) {
メソッドは基本的に振る舞いになるので、L18のように名詞ではなく動詞付きで表現することが多いですかね〜
なので動詞付きの命名で検討してみてください！

2022-12-01 21:37 UTC, YudaiNoda3576 commented on HelloWorld/src/main/java/com/raisetech/HelloWorld/controller/HelloController.java
> +		String ope = languageAge.getOpe();
`ope`はなんの省略なのでしょうか？？

2022-12-01 21:37 UTC, YudaiNoda3576 commented on HelloWorld/src/main/java/com/raisetech/HelloWorld/controller/HelloController.java
> +		DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
`dtf`は`DateTimeFormatter`が横にあるかつローカル変数だから許容できるかなという感じがします！

2022-12-01 21:37 UTC, YudaiNoda3576 commented on HelloWorld/src/main/java/com/raisetech/HelloWorld/controller/HelloController.java
> +			case "JAPAN", "KOREAN" -> {
`JAPAN`などの国名は定数で持っておくかEnumで持っておくかしてもいいかもですね！
せっかくなのでEnumを使ってみてください！

2022-12-01 21:37 UTC, YudaiNoda3576 commented on HelloWorld/src/main/java/com/raisetech/HelloWorld/controller/HelloController.java
> +	private void setGreetingAndTodayDate(FDat fdat) {
以下でしてきしてますのでそちらで続きのやり取りをしましょう！

2022-12-02 09:20 UTC, kazuoikeda1411 commented on HelloWorld/src/main/java/com/raisetech/HelloWorld/controller/HelloController.java
> +		String isGreeting = "";
承知しました！
`greeting`にて修正しました！

2022-12-02 09:24 UTC, kazuoikeda1411 commented on HelloWorld/src/main/java/com/raisetech/HelloWorld/controller/HelloController.java
> +	@GetMapping ("/language-age")
パスを複数形に変更しました！ 
パスの命名については仕様変更のことまで考えて決めないといけないのですね、、、
今後気をつけます！

2022-12-02 09:27 UTC, kazuoikeda1411 commented on HelloWorld/src/main/java/com/raisetech/HelloWorld/controller/HelloController.java
> +		model.addAttribute("languageAge", new FDat());
時刻の情報も格納しているので、FDatクラス名をUserDateに変更しました。

2022-12-02 09:30 UTC, kazuoikeda1411 commented on HelloWorld/src/main/java/com/raisetech/HelloWorld/controller/HelloController.java
> +	public String selfIntroduction(
tmp_result.htmlに処理した値をpostしていると考え`postSelfIntroduction`に変更しました。

2022-12-02 09:34 UTC, kazuoikeda1411 commented on HelloWorld/src/main/java/com/raisetech/HelloWorld/controller/HelloController.java
> +	public String languageAge(Model model) {
`getLanguageAge`に変更しました！

2022-12-02 09:37 UTC, kazuoikeda1411 commented on HelloWorld/src/main/java/com/raisetech/HelloWorld/controller/HelloController.java
> +		String ope = languageAge.getOpe();
参考にしたコードからの変更が漏れていました、、、
（operationの略だと思います）
`country`に変更しました！

2022-12-02 09:48 UTC, kazuoikeda1411 commented on HelloWorld/src/main/java/com/raisetech/HelloWorld/controller/HelloController.java
> +			case "JAPAN", "KOREAN" -> {
Enumを使ってコードを記載してみました！
正直使い方が合っている気がしないです、、、

`/self-introductions`で言語は選択肢以外入力できないようになっているので、
今回のケースでは国名を定数で持っておく（←表現がよく理解できてない箇所）必要がないのではと
考えました。。。

ご確認お願いします🙇

2022-12-02 09:52 UTC, kazuoikeda1411 commented
ご確認ありがとうございます！
コメントいただいた箇所を修正致しました。
ご角煮の願いいたします！

2022-12-02 22:46 UTC, YudaiNoda3576 commented
![LGTM](https://images.lgtmgen.org/2d4d8410-c3ce-4b7c-9416-f30f0d3522e7)

2022-12-02 23:50 UTC, merged